branches:
  # Maintenance release branches
  - '+([0-9])?(.{+([0-9]),x}).x'
  # Release branches
  - latest
  # Prerelease branches
  - name: main
    channel: next
    prerelease: next
  - name: beta
    prerelease: true
  - name: alpha
    prerelease: true

plugins:
  - '@semantic-release/commit-analyzer'
  - '@semantic-release/release-notes-generator'
  - - '@semantic-release/changelog'
    - changelogTitle: '# Changelog'
  - '@semantic-release/npm'
  - - '@semantic-release/git'
    - assets:
        - 'package.json'
        - 'package-lock.json'
        - 'CHANGELOG.md'
      message: "chore(release): ${nextRelease.version} [skip ci]\n\n${nextRelease.notes}"
  - '@semantic-release/github'
