name: Test Coveralls

on: ['push', 'pull_request']

jobs:
  coverage:
    name: Coverage
    runs-on: ubuntu-latest

    # Prevent on version bump
    if: "!contains(github.event.head_commit.author.name, 'Bump version')"

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
      - name: npm install
        run: npm ci
      - name: coverage report
        run: npm run test:coverage
      - name: Coveralls
        uses: coverallsapp/github-action@master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
